apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-layer
  labels:
    app: api-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-layer
  template:
    metadata:
      labels:
        app: api-layer
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z -w1 mysql-newrelic-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: api-layer
          image: mysql-newrelic-k6-api-layer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: "mysql-newrelic-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "dummy_local_password"
            - name: MYSQL_DATABASE
              value: "employees"
            - name: NEW_RELIC_LICENSE_KEY
              value: "dummy_local_dev_license_key_12345"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
