apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      component: database
  template:
    metadata:
      labels:
        app: mysql
        component: database
      annotations:
        newrelic.io/monitor: "true"
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      volumes:
        - name: newrelic-infra-config
          configMap:
            name: newrelic-infra-config
        - name: mysql-integration-config
          configMap:
            name: mysql-integration-config
        - name: mysql-data
          emptyDir: 
            sizeLimit: 5Gi
      initContainers:
        - name: init-mysql-data-dir
          image: busybox:1.36
          command: ['sh', '-c', 'mkdir -p /var/lib/mysql/data && chmod 750 /var/lib/mysql/data']
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql-newrelic-k6-mysql:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: employees
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - mysql
                - -h
                - localhost
                - -e
                - "SELECT 1"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - mysql
                - -h
                - localhost
                - -e
                - "SELECT 1"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
        - name: newrelic-infra
          image: newrelic/infrastructure:latest
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: NEW_RELIC_LICENSE_KEY
            - name: NRIA_VERBOSE
              value: "1"
            - name: NRIA_DISPLAY_NAME
              value: "mysql-$(NODE_NAME)"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: newrelic-infra-config
              mountPath: /etc/newrelic-infra.yml
              subPath: newrelic-infra.yml
            - name: mysql-integration-config
              mountPath: /etc/newrelic-infra/integrations.d/mysql-config.yml
              subPath: mysql-config.yml
          resources:
            limits:
              memory: 300Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 100m
          securityContext:
            privileged: true
