# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push MySQL Image
        run: |
          docker build -f Dockerfile.mysql -t ${{ secrets.DOCKERHUB_USERNAME }}/mysql-newrelic:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mysql-newrelic:latest

      - name: Build & Push API Layer Image
        run: |
          cd api-layer
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-layer:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-layer:latest

      - name: Build & Push Load Generator Image
        run: |
          cd ../load-generator
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/load-generator:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/load-generator:latest

      - name: Set Kubernetes Context
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/secrets.yaml
          kubectl apply -f k8s/mysql-pvc.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/api-layer-deployment.yaml
          kubectl apply -f k8s/api-layer-service.yaml
          kubectl apply -f k8s/load-generator-deployment.yaml
          kubectl apply -f k8s/load-generator-hpa.yaml
          kubectl apply -f k8s/network-policy.yaml
